server:
  port: 28080
  address: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://prod-db-server:3306/wecube_core_04?characterEncoding=utf8&serverTimezone=UTC
    username: db-user
    password: db-password

wecube:
  core:
    s3:
      endpoint: http://prod-s3-server:9000
      access-key: access_key
      secret-key: secret_key