SET FOREIGN_KEY_CHECKS = 0;

alter table plugin_packages convert to character set utf8 collate utf8_bin;
alter table plugin_package_dependencies convert to character set utf8 collate utf8_bin;
alter table plugin_package_menus convert to character set utf8 collate utf8_bin;
alter table plugin_package_data_model convert to character set utf8 collate utf8_bin;
alter table plugin_package_entities convert to character set utf8 collate utf8_bin;
alter table plugin_package_attributes convert to character set utf8 collate utf8_bin;
alter table system_variables convert to character set utf8 collate utf8_bin;
alter table plugin_package_authorities convert to character set utf8 collate utf8_bin;
alter table plugin_package_runtime_resources_docker convert to character set utf8 collate utf8_bin;
alter table plugin_package_runtime_resources_mysql convert to character set utf8 collate utf8_bin;
alter table plugin_package_runtime_resources_s3 convert to character set utf8 collate utf8_bin;
alter table plugin_configs convert to character set utf8 collate utf8_bin;
alter table plugin_config_interfaces convert to character set utf8 collate utf8_bin;
alter table plugin_config_interface_parameters convert to character set utf8 collate utf8_bin;
alter table menu_items convert to character set utf8 collate utf8_bin;
alter table plugin_package_resource_files convert to character set utf8 collate utf8_bin;
alter table resource_server convert to character set utf8 collate utf8_bin;
alter table resource_item convert to character set utf8 collate utf8_bin;
alter table plugin_instances convert to character set utf8 collate utf8_bin;
alter table plugin_mysql_instances convert to character set utf8 collate utf8_bin;
alter table role_menu convert to character set utf8 collate utf8_bin;
alter table batch_execution_jobs convert to character set utf8 collate utf8_bin;
alter table execution_jobs convert to character set utf8 collate utf8_bin;
alter table execution_job_parameters convert to character set utf8 collate utf8_bin;
alter table favorites convert to character set utf8 collate utf8_bin;
alter table favorites_role convert to character set utf8 collate utf8_bin;
alter table plugin_artifact_pull_req convert to character set utf8 collate utf8_bin;
alter table act_ru_procinst_status convert to character set utf8 collate utf8_bin;
alter table act_ru_srvnode_status convert to character set utf8 collate utf8_bin;
alter table core_operation_event convert to character set utf8 collate utf8_bin;
alter table core_re_proc_def_info convert to character set utf8 collate utf8_bin;
alter table core_re_task_node_def_info convert to character set utf8 collate utf8_bin;
alter table core_re_task_node_param convert to character set utf8 collate utf8_bin;
alter table core_ru_graph_node convert to character set utf8 collate utf8_bin;
alter table core_ru_proc_exec_binding convert to character set utf8 collate utf8_bin;
alter table core_ru_proc_exec_binding_tmp convert to character set utf8 collate utf8_bin;
alter table core_ru_proc_inst_info convert to character set utf8 collate utf8_bin;
alter table core_ru_proc_role_binding convert to character set utf8 collate utf8_bin;
alter table core_ru_task_node_exec_param convert to character set utf8 collate utf8_bin;
alter table core_ru_task_node_exec_req convert to character set utf8 collate utf8_bin;
alter table core_ru_task_node_inst_info convert to character set utf8 collate utf8_bin;
alter table plugin_config_roles convert to character set utf8 collate utf8_bin;
alter table core_object_meta convert to character set utf8 collate utf8_bin;
alter table core_object_property_meta convert to character set utf8 collate utf8_bin;
alter table core_object_var convert to character set utf8 collate utf8_bin;
alter table core_object_property_var convert to character set utf8 collate utf8_bin;
alter table core_object_list_var convert to character set utf8 collate utf8_bin;


SET FOREIGN_KEY_CHECKS = 1;