version: '2'
services:
  admin-user-mgmt:
    image: platform-auth-server:{{version}}
    container_name: platform-auth-server-{{version}}
    restart: always
    ports:
      - [@HOSTIP]:[#port]:8080
    volumes:
      - /etc/localtime:/etc/localtime
      - [#path]/logs:/app/platform-auth-server/logs
      - [#path]/config/private_keys:/app/platform-auth-server/config/private_keys
      - [#path]/config/public_keys:/app/platform-auth-server/config/public_keys
    environment:
      - server_port=8080
      - log_level=[#log_level]
      - db_server=[#db_server]
      - db_port=[#db_port]
      - db_user=[#db_user]
      - db_pass=[#db_pass]
      - db_database=[#db_database]
      - auth_access_token_mins=[#auth_access_token_mins]
      - auth_refresh_token_hours=[#auth_refresh_token_hours]
      - source_auth_enable=[#source_auth_enable]
      - um_address=[#um_address]
      - um_app_id=[#um_app_id]
      - um_app_token=[#um_app_token]
      - server_http_host=[@HOSTIP]
      - server_http_port=[#port]
      - jwt_private_key_path=[#jwt_private_key_path]
      - jwt_public_key_path=[#jwt_public_key_path]
      - source_auth_private_key_path=[#source_auth_private_key_path]
      - source_auth_public_key_dir=[#source_auth_public_key_dir]
      - um_permission_system_id=[#um_permission_system_id]
      - um_permission_address=http://[@UM_UMAPP_VIP]:[@UM_UMAPP_PORT]
      - um_permission_cron_express=[#um_permission_cron_express]

