server:
   port: 19110
   ssl:
      enabled: false
      key-alias: gw
      key-store-password: 123456
      key-store: classpath:gw-keystore.p12
      key-store-type: PKCS12
logging:
   config: classpath:logback-spring.xml

platform:
   gateway:
      route:
         route-config-server: http://10.0.0.17:19100
         route-config-uri: /platform/v1/route-items
         route-config-access-key: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXRUNVQkUtQ09SRSIsImlhdCI6MTU3MDY5MDMwMCwidHlwZSI6ImFjY2Vzc1Rva2VuIiwiY2xpZW50VHlwZSI6IlNVQl9TWVNURU0iLCJleHAiOjE2MDIzMTI3MDAsImF1dGhvcml0eSI6IltTVUJfU1lTVEVNXSJ9.Mq8g_ZoPIQ_mB59zEq0KVtwGn_uPqL8qn6sP7WzEiJxoXQQIcVe7mYsG-E2jxCShEQL7PsMNLM47MYuY7R5nBg

spring:
   cloud:
      gateway:
         httpclient:
            ssl:
               useInsecureTrustManager: true
         routes:
            - id: platform-core
              uri: http://10.0.0.17:19100
              predicates:
                 - Path=/platform/**
              filters:
                 - DynamicRoute=false
            - id: platform-auth-server
              uri: http://10.0.0.17:19120
              predicates:
                 - Path=/auth/**
              filters:
                 - DynamicRoute=false
