//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.09 at 03:29:54 PM CST 
//


package com.webank.wecube.platform.core.service.plugin.xml.register;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for packageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="packageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="packageDependencies" type="{}packageDependenciesType" minOccurs="0"/>
 *         &lt;element name="menus" type="{}menusType" minOccurs="0"/>
 *         &lt;element name="dataModel" type="{}dataModelType" minOccurs="0"/>
 *         &lt;element name="systemParameters" type="{}systemParametersType" minOccurs="0"/>
 *         &lt;element name="authorities" type="{}authoritiesType" minOccurs="0"/>
 *         &lt;element name="resourceDependencies" type="{}resourceDependenciesType"/>
 *         &lt;element name="plugins" type="{}pluginsType" minOccurs="0"/>
 *         &lt;element name="paramObjects" type="{}paramObjectsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "package", namespace = "")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "packageType", propOrder = {
    "packageDependencies",
    "menus",
    "dataModel",
    "systemParameters",
    "authorities",
    "resourceDependencies",
    "paramObjects",
    "plugins"
})
public class PackageType {

    protected PackageDependenciesType packageDependencies;
    protected MenusType menus;
    protected DataModelType dataModel;
    protected SystemParametersType systemParameters;
    protected AuthoritiesType authorities;
    @XmlElement(required = true)
    protected ResourceDependenciesType resourceDependencies;
    protected PluginsType plugins;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "version")
    protected String version;
    protected ParamObjectsType paramObjects;

    /**
     * Gets the value of the packageDependencies property.
     * 
     * @return
     *     possible object is
     *     {@link PackageDependenciesType }
     *     
     */
    public PackageDependenciesType getPackageDependencies() {
        return packageDependencies;
    }

    /**
     * Sets the value of the packageDependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageDependenciesType }
     *     
     */
    public void setPackageDependencies(PackageDependenciesType value) {
        this.packageDependencies = value;
    }

    /**
     * Gets the value of the menus property.
     * 
     * @return
     *     possible object is
     *     {@link MenusType }
     *     
     */
    public MenusType getMenus() {
        return menus;
    }

    /**
     * Sets the value of the menus property.
     * 
     * @param value
     *     allowed object is
     *     {@link MenusType }
     *     
     */
    public void setMenus(MenusType value) {
        this.menus = value;
    }

    /**
     * Gets the value of the dataModel property.
     * 
     * @return
     *     possible object is
     *     {@link DataModelType }
     *     
     */
    public DataModelType getDataModel() {
        return dataModel;
    }

    /**
     * Sets the value of the dataModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataModelType }
     *     
     */
    public void setDataModel(DataModelType value) {
        this.dataModel = value;
    }

    /**
     * Gets the value of the systemParameters property.
     * 
     * @return
     *     possible object is
     *     {@link SystemParametersType }
     *     
     */
    public SystemParametersType getSystemParameters() {
        return systemParameters;
    }

    /**
     * Sets the value of the systemParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemParametersType }
     *     
     */
    public void setSystemParameters(SystemParametersType value) {
        this.systemParameters = value;
    }

    /**
     * Gets the value of the authorities property.
     * 
     * @return
     *     possible object is
     *     {@link AuthoritiesType }
     *     
     */
    public AuthoritiesType getAuthorities() {
        return authorities;
    }

    /**
     * Sets the value of the authorities property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthoritiesType }
     *     
     */
    public void setAuthorities(AuthoritiesType value) {
        this.authorities = value;
    }

    /**
     * Gets the value of the resourceDependencies property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceDependenciesType }
     *     
     */
    public ResourceDependenciesType getResourceDependencies() {
        return resourceDependencies;
    }

    /**
     * Sets the value of the resourceDependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceDependenciesType }
     *     
     */
    public void setResourceDependencies(ResourceDependenciesType value) {
        this.resourceDependencies = value;
    }

    /**
     * Gets the value of the plugins property.
     * 
     * @return
     *     possible object is
     *     {@link PluginsType }
     *     
     */
    public PluginsType getPlugins() {
        return plugins;
    }

    /**
     * Sets the value of the plugins property.
     * 
     * @param value
     *     allowed object is
     *     {@link PluginsType }
     *     
     */
    public void setPlugins(PluginsType value) {
        this.plugins = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    public ParamObjectsType getParamObjects() {
        return paramObjects;
    }

    public void setParamObjects(ParamObjectsType paramObjects) {
        this.paramObjects = paramObjects;
    }

    
}
