//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.24 at 03:15:42 PM CST 
//

package com.webank.wecube.platform.core.service.plugin.xml.register;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for paramPropertyType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="paramPropertyType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="refType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mapType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mapExpr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sensitiveData" type="{http://www.w3.org/2001/XMLSchema}string" default="N" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paramPropertyType", propOrder = { "value" })
public class ParamPropertyType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "dataType", required = true)
    protected String dataType;
    @XmlAttribute(name = "multiple")
    protected String multiple;
    @XmlAttribute(name = "refObjectName")
    protected String refObjectName;
    @XmlAttribute(name = "mapType")
    protected String mapType;
    @XmlAttribute(name = "mapExpr")
    protected String mapExpr;
    @XmlAttribute(name = "sensitiveData")
    protected String sensitiveData;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the mapType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMapType() {
        return mapType;
    }

    /**
     * Sets the value of the mapType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMapType(String value) {
        this.mapType = value;
    }

    /**
     * Gets the value of the mapExpr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMapExpr() {
        return mapExpr;
    }

    /**
     * Sets the value of the mapExpr property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMapExpr(String value) {
        this.mapExpr = value;
    }

    /**
     * Gets the value of the sensitiveData property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSensitiveData() {
        if (sensitiveData == null) {
            return "N";
        } else {
            return sensitiveData;
        }
    }

    /**
     * Sets the value of the sensitiveData property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSensitiveData(String value) {
        this.sensitiveData = value;
    }

    public String getMultiple() {
        return multiple;
    }

    public void setMultiple(String multiple) {
        this.multiple = multiple;
    }

    public String getRefObjectName() {
        return refObjectName;
    }

    public void setRefObjectName(String refObjectName) {
        this.refObjectName = refObjectName;
    }

    

}
