//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.09 at 03:29:54 PM CST 
//


package com.webank.wecube.platform.core.service.plugin.xml.register;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pluginType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pluginType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="roleBinds" type="{}roleBindsType" minOccurs="0"/>
 *         &lt;element name="interface" type="{}interfaceType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="targetPackage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="targetEntity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="targetEntityFilterRule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="registerName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pluginType", propOrder = {
    "roleBinds",
    "_interface"
})
public class PluginType {

    protected RoleBindsType roleBinds;
    @XmlElement(name = "interface", required = true)
    protected List<InterfaceType> _interface;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "targetPackage")
    protected String targetPackage;
    @XmlAttribute(name = "targetEntity")
    protected String targetEntity;
    @XmlAttribute(name = "targetEntityFilterRule")
    protected String targetEntityFilterRule;
    @XmlAttribute(name = "registerName")
    protected String registerName;

    /**
     * Gets the value of the roleBinds property.
     * 
     * @return
     *     possible object is
     *     {@link RoleBindsType }
     *     
     */
    public RoleBindsType getRoleBinds() {
        return roleBinds;
    }

    /**
     * Sets the value of the roleBinds property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleBindsType }
     *     
     */
    public void setRoleBinds(RoleBindsType value) {
        this.roleBinds = value;
    }

    /**
     * Gets the value of the interface property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interface property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterface().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterfaceType }
     * 
     * 
     */
    public List<InterfaceType> getInterface() {
        if (_interface == null) {
            _interface = new ArrayList<InterfaceType>();
        }
        return this._interface;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the targetPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetPackage() {
        return targetPackage;
    }

    /**
     * Sets the value of the targetPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetPackage(String value) {
        this.targetPackage = value;
    }

    /**
     * Gets the value of the targetEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetEntity() {
        return targetEntity;
    }

    /**
     * Sets the value of the targetEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetEntity(String value) {
        this.targetEntity = value;
    }

    /**
     * Gets the value of the targetEntityFilterRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetEntityFilterRule() {
        return targetEntityFilterRule;
    }

    /**
     * Sets the value of the targetEntityFilterRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetEntityFilterRule(String value) {
        this.targetEntityFilterRule = value;
    }

    /**
     * Gets the value of the registerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisterName() {
        return registerName;
    }

    /**
     * Sets the value of the registerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisterName(String value) {
        this.registerName = value;
    }

}
