//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.09 at 03:29:54 PM CST 
//


package com.webank.wecube.platform.core.service.plugin.xml.register;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resourceDependenciesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourceDependenciesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="docker" type="{}dockerType" maxOccurs="unbounded"/>
 *         &lt;element name="mysql" type="{}mysqlType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="s3" type="{}s3Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourceDependenciesType", propOrder = {
    "docker",
    "mysql",
    "s3"
})
public class ResourceDependenciesType {

    @XmlElement(required = true)
    protected List<DockerType> docker;
    protected List<MysqlType> mysql;
    protected List<S3Type> s3;

    /**
     * Gets the value of the docker property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the docker property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocker().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DockerType }
     * 
     * 
     */
    public List<DockerType> getDocker() {
        if (docker == null) {
            docker = new ArrayList<DockerType>();
        }
        return this.docker;
    }

    /**
     * Gets the value of the mysql property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mysql property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMysql().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MysqlType }
     * 
     * 
     */
    public List<MysqlType> getMysql() {
        if (mysql == null) {
            mysql = new ArrayList<MysqlType>();
        }
        return this.mysql;
    }

    /**
     * Gets the value of the s3 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the s3 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getS3().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link S3Type }
     * 
     * 
     */
    public List<S3Type> getS3() {
        if (s3 == null) {
            s3 = new ArrayList<S3Type>();
        }
        return this.s3;
    }

}
