name: Synchronize latest published release to Gitee
on:
  push:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  sync-published-release:
    name: Synchronize latest published release to Gitee
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sh build/sync-github-latest-release-to-gitee.sh
      env:
        GITEE_API_TOKEN: ${{ secrets.GITEE_API_TOKEN }}
