name: Synchronize release
on:
  release:
    types: [published, edited]
  workflow_dispatch:
jobs:
  sync-published-release:
    name: Synchronize release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: build/sync-github-release-to-gitee.sh
      shell: bash
      env:
        GITEE_API_TOKEN: ${{ secrets.GITEE_API_TOKEN }}
